export const ACTIONS = {
  ADD_MEAL: "ADD_MEAL",
  GET_MEALS_FROM_SERVER_DONE: "GET_MEALS_FROM_SERVER_DONE",
  REMOVE_MEAL: "REMOVE_MEAL",
  CONFIG: {
    CHANGE_STARS_COLOR: "CHANGE_STARS_COLOR",
  },
};
